FROM postgres

USER postgres

RUN    /etc/init.d/postgresql start &&\
    psql --command "CREATE USER $POSTGRES_USER WITH SUPERUSER PASSWORD $POSTGRES_PASSWORD;" &&\
    createdb -O $POSTGRES_DB $POSTGRES_USER
